### ISSUE TITLE
PGA functions 

### ISSUE THREAD

**Issue by sdaprix23** [zamorarr/coach#15]
Any plans on adding the PGA functions for DK/FD?  Love the NFL optimizer BTW

**Comment by zamorarr** [comment]
hi @sdaprix23 are you still interested in this? I can add it to my list of things to start working on again

**Comment by sdaprix23** [comment]
Yes please!  PGA is just now getting going again

**Comment by zamorarr** [comment]
Hey @sdaprix23 I updated the package to include `model_dk_pga()` and `model_fd_pga()`. You'll have to re-install the package from Github to see the changes. Let me know if it everything works ok!

**Comment by themultiv3rs3** [comment]
This is working great. I did notice one small issue when trying to use the write function:

Error in match.arg(sport) : 
  'arg' should be one of “nfl”, “mlb”, “nba”, “nhl”, “nascar”

**Comment by zamorarr** [comment]
Ah thanks for letting me know. I'll get that fixed tomorrow

**Comment by sdaprix23** [comment]
Thanks for updating this for PGA.  I've been away from it for a while.  There is an error when using the write-lineups as noted by algosync.  I just updated to the newest available and can confirm the print error still exists.  

> write_lineups(lineups, "mylineups.csv", site = "draftkings", sport = "pga")
Error in match.arg(sport) : 
  'arg' should be one of “nfl”, “mlb”, “nba”, “nhl”, “nascar”

**Comment by zamorarr** [comment]
Hi @sdaprix23. This should be fixed now in #21. Can you re-install the latest version of coach from github and try again? Let me know if you have any issues.

**Comment by sdaprix23** [comment]
Works perfect!  Thanks again for adding this.
